"""Pin the consolidated open-now vocab to its pre-consolidation behavior.

Issue 3 (2026-06-18) derived the three open-now matchers from one canonical list
in ``app.chat.open_now_vocab``. This test locks that refactor to be
behavior-identical:

  * the Tier-1 detector regex is regenerated byte-for-byte,
  * the capture→canonical dict is unchanged,
  * the bare-listing regex still captures the same category for a matrix of
    inputs (including the grocery pass-through, ``pub``→``bar`` remap, and the
    ``store`` / ``hardware store`` / ``coffee shop`` overlaps),
  * the two consumer modules use the SAME objects (no silent fork).

``tests/test_open_now_vocab_alignment.py`` remains the drift guard across the
three matchers; this test guards the consolidation itself.
"""

from __future__ import annotations

import pytest

from app.chat import entity_intent
from app.chat import tier2_business_shortcut as shortcut
from app.chat.entity_intent import is_category_open_now_listing
from app.chat.open_now_vocab import (
    BARE_OPEN_NOW_RE,
    CATEGORY_OPEN_NOW_RE,
    OPEN_NOW_CAPTURE_TO_CATEGORY,
)
from app.chat.tier2_business_shortcut import _category_from_open_now_capture

# The exact pre-consolidation _CATEGORY_OPEN_NOW_RE pattern (entity_intent.py).
_LEGACY_CATEGORY_PATTERN = (
    r"\b(?:restaurants?|cafes?|coffee\s+shops?|bars?|pubs?|brewer(?:y|ies)|"
    r"veterinarians?|vets?|pharmac(?:y|ies)|groceries|grocery\s+stores?|stores?|"
    r"shops?|gyms?|plumbers?|electricians?|hvac|locksmiths?|mechanics?|"
    r"auto\s+repair|dentists?|doctors?|clinics?|urgent\s+care|salons?|"
    r"barbers?|groomers?|hardware\s+stores?)\b"
)

_LEGACY_DICT = {
    "restaurant": "restaurant", "restaurants": "restaurant",
    "cafe": "cafe", "cafes": "cafe",
    "coffee shop": "coffee shop", "coffee shops": "coffee shop",
    "bar": "bar", "bars": "bar",
    "pharmacy": "pharmacy", "pharmacies": "pharmacy",
    "vet": "veterinarian", "vets": "veterinarian",
    "veterinarian": "veterinarian", "veterinarians": "veterinarian",
    "store": "store", "stores": "store",
    "shop": "shop", "shops": "shop",
    "gym": "gym", "gyms": "gym",
    "pub": "bar", "pubs": "bar",
    "brewery": "brewery", "breweries": "brewery",
    "plumber": "plumber", "plumbers": "plumber",
    "electrician": "electrician", "electricians": "electrician",
    "hvac": "hvac",
    "locksmith": "locksmith", "locksmiths": "locksmith",
    "mechanic": "mechanic", "mechanics": "mechanic",
    "auto repair": "auto repair",
    "dentist": "dentist", "dentists": "dentist",
    "doctor": "doctor", "doctors": "doctor",
    "clinic": "clinic", "clinics": "clinic",
    "urgent care": "urgent care",
    "salon": "salon", "salons": "salon",
    "barber": "barber", "barbers": "barber",
    "groomer": "groomer", "groomers": "groomer",
    "hardware store": "hardware store", "hardware stores": "hardware store",
}


def test_category_regex_regenerated_byte_for_byte() -> None:
    assert CATEGORY_OPEN_NOW_RE.pattern == _LEGACY_CATEGORY_PATTERN


def test_capture_dict_unchanged() -> None:
    assert OPEN_NOW_CAPTURE_TO_CATEGORY == _LEGACY_DICT


def test_consumer_modules_share_the_canonical_objects() -> None:
    # No silent fork — both modules use the exact compiled objects / dict.
    assert entity_intent._CATEGORY_OPEN_NOW_RE is CATEGORY_OPEN_NOW_RE
    assert shortcut._BARE_OPEN_NOW_RE is BARE_OPEN_NOW_RE
    assert shortcut._OPEN_NOW_CAPTURE_TO_CATEGORY is OPEN_NOW_CAPTURE_TO_CATEGORY


@pytest.mark.parametrize(
    "query,expected_category",
    [
        ("restaurants open now", "restaurant"),
        ("restaurant open right now", "restaurant"),
        ("coffee shop open now", "coffee shop"),
        ("coffee shops open right now", "coffee shop"),
        ("pub open now", "bar"),  # pub remaps to bar
        ("pubs open now", "bar"),
        ("brewery open now", "brewery"),
        ("breweries open now", "brewery"),
        ("vets open now", "veterinarian"),
        ("veterinarian open now", "veterinarian"),
        ("hardware store open now", "hardware store"),  # not "store"
        ("auto repair open now", "auto repair"),
        ("urgent care open now", "urgent care"),
        # grocery forms match the regex but pass through unremapped (no dict entry).
        ("grocery store open now", "grocery store"),
        ("groceries open now", "groceries"),
    ],
)
def test_bare_listing_captures_expected_category(query: str, expected_category: str) -> None:
    m = BARE_OPEN_NOW_RE.match(query)
    assert m is not None, f"{query!r} should match the bare open-now shape"
    assert _category_from_open_now_capture(m.group(1)) == expected_category


@pytest.mark.parametrize(
    "query,expected",
    [
        ("restaurants open now", True),
        ("is the pharmacy open right now", True),
        ("hardware store open now", True),
        ("grocery store open now", True),
        ("saloon open now", False),  # 'saloon' is not 'salon' — no token match
        ("foobar open now", False),
        ("restaurants open later", False),  # no open-now phrase
    ],
)
def test_detector_matches_expected(query: str, expected: bool) -> None:
    assert is_category_open_now_listing(query) is expected
