"""Regression gate: every phrase in the bank routes to its labeled intent.

The bank (tests/fixtures/intent_phrase_bank.json) is generated by the Phase-2
workflow and validated against the real resolver by
scripts/build_intent_phrase_bank.py -- only phrases that route as labeled are
committed. This test re-asserts that on every run, so a resolver change that
breaks established routing fails CI. DB-free (resolver is pure), so it runs in
the fast unit lane.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.chat.intents.resolver import resolve

_BANK = json.loads(
    (Path(__file__).parent / "fixtures" / "intent_phrase_bank.json").read_text(encoding="utf-8")
)
_CASES = [(intent, phrase) for intent, phrases in _BANK.items() for phrase in phrases]


@pytest.mark.parametrize(
    "intent,phrase",
    _CASES,
    ids=[f"{intent}:{phrase[:28]}" for intent, phrase in _CASES],
)
def test_phrase_routes_to_intent(intent: str, phrase: str) -> None:
    resolved = resolve(phrase)
    assert resolved is not None, f"{phrase!r} fell through (expected {intent})"
    assert resolved.intent_key == intent, (
        f"{phrase!r} routed to {resolved.intent_key}, expected {intent}"
    )


def test_bank_covers_phase1_intents() -> None:
    # Each Phase-1 intent should carry a substantive phrase bank.
    for intent, phrases in _BANK.items():
        assert len(phrases) >= 15, f"{intent} bank is thin ({len(phrases)})"
    assert len(_CASES) >= 400
