"""Single source of truth for the open-now category vocabulary.

The "<category> open now" vocab used to be spelled out in three places that had
to be hand-kept in sync:

  * ``entity_intent._CATEGORY_OPEN_NOW_RE`` — the Tier-1-suppression detector
    (``.search`` anywhere in the query),
  * ``tier2_business_shortcut._BARE_OPEN_NOW_RE`` — the deterministic bare
    "<category> open now" listing shape (anchored ``.match``),
  * ``tier2_business_shortcut._OPEN_NOW_CAPTURE_TO_CATEGORY`` — capture →
    canonical-category remap.

This module derives all three from one ordered list so a category can't be
added to one matcher but forgotten in another. ``tests/test_open_now_vocab_alignment.py``
remains the drift guard; ``tests/test_open_now_vocab_consolidation.py`` pins the
generated regexes/dict so the consolidation stays behavior-identical.

Each ``_OPEN_NOW_VOCAB`` entry is ``(regex_fragment, capture_map)``:

  * ``regex_fragment`` is the surface alternation (e.g. ``r"restaurants?"``,
    ``r"coffee\\s+shops?"``, ``r"brewer(?:y|ies)"``). It feeds BOTH regexes.
  * ``capture_map`` maps each concrete surface form to its canonical category
    for the Tier-2 filter. It is intentionally EMPTY for forms that pass through
    unremapped (grocery): the original dict never remapped those, and
    ``_category_from_open_now_capture`` falls back to the raw capture, so leaving
    them out preserves the exact prior behavior.

Ordering matches the original ``_CATEGORY_OPEN_NOW_RE`` alternation so that
regex is regenerated byte-for-byte; the bare regex differs only in alternation
order, which is immaterial here (every alternative is a whole-token match bounded
by ``\\b`` / the anchors, so the leftmost-longest result is order-independent —
verified exhaustively in the consolidation test).
"""

from __future__ import annotations

import re

# (regex fragment, {surface form: canonical category}). Order mirrors the legacy
# _CATEGORY_OPEN_NOW_RE alternation.
_OPEN_NOW_VOCAB: tuple[tuple[str, dict[str, str]], ...] = (
    (r"restaurants?", {"restaurant": "restaurant", "restaurants": "restaurant"}),
    (r"cafes?", {"cafe": "cafe", "cafes": "cafe"}),
    (r"coffee\s+shops?", {"coffee shop": "coffee shop", "coffee shops": "coffee shop"}),
    (r"bars?", {"bar": "bar", "bars": "bar"}),
    (r"pubs?", {"pub": "bar", "pubs": "bar"}),
    (r"brewer(?:y|ies)", {"brewery": "brewery", "breweries": "brewery"}),
    (r"veterinarians?", {"veterinarian": "veterinarian", "veterinarians": "veterinarian"}),
    (r"vets?", {"vet": "veterinarian", "vets": "veterinarian"}),
    (r"pharmac(?:y|ies)", {"pharmacy": "pharmacy", "pharmacies": "pharmacy"}),
    # grocery forms match in both regexes but were never in the remap dict — they
    # pass through as the raw capture, so the maps stay empty (behavior-preserving).
    (r"groceries", {}),
    (r"grocery\s+stores?", {}),
    (r"stores?", {"store": "store", "stores": "store"}),
    (r"shops?", {"shop": "shop", "shops": "shop"}),
    (r"gyms?", {"gym": "gym", "gyms": "gym"}),
    (r"plumbers?", {"plumber": "plumber", "plumbers": "plumber"}),
    (r"electricians?", {"electrician": "electrician", "electricians": "electrician"}),
    (r"hvac", {"hvac": "hvac"}),
    (r"locksmiths?", {"locksmith": "locksmith", "locksmiths": "locksmith"}),
    (r"mechanics?", {"mechanic": "mechanic", "mechanics": "mechanic"}),
    (r"auto\s+repair", {"auto repair": "auto repair"}),
    (r"dentists?", {"dentist": "dentist", "dentists": "dentist"}),
    (r"doctors?", {"doctor": "doctor", "doctors": "doctor"}),
    (r"clinics?", {"clinic": "clinic", "clinics": "clinic"}),
    (r"urgent\s+care", {"urgent care": "urgent care"}),
    (r"salons?", {"salon": "salon", "salons": "salon"}),
    (r"barbers?", {"barber": "barber", "barbers": "barber"}),
    (r"groomers?", {"groomer": "groomer", "groomers": "groomer"}),
    (r"hardware\s+stores?", {"hardware store": "hardware store", "hardware stores": "hardware store"}),
)

#: Surface alternation fragments, in canonical order. Feeds both regexes.
OPEN_NOW_FRAGMENTS: tuple[str, ...] = tuple(frag for frag, _ in _OPEN_NOW_VOCAB)

_ALT = "|".join(OPEN_NOW_FRAGMENTS)

#: Tier-1-suppression detector: a category open-now noun anywhere in the query.
CATEGORY_OPEN_NOW_RE = re.compile(r"\b(?:" + _ALT + r")\b", re.IGNORECASE)

#: Deterministic bare "<category> open now" listing shape (anchored, capturing).
BARE_OPEN_NOW_RE = re.compile(
    r"^(" + _ALT + r")\s+open\s+(?:now|right\s+now)\s*$",
    re.IGNORECASE,
)

#: Captured surface form → canonical category. Forms absent here pass through as
#: the raw capture (see _category_from_open_now_capture).
OPEN_NOW_CAPTURE_TO_CATEGORY: dict[str, str] = {}
for _frag, _capture_map in _OPEN_NOW_VOCAB:
    OPEN_NOW_CAPTURE_TO_CATEGORY.update(_capture_map)
