"""Dedup the Havasu Lanes glow-bowling double-listing (2026-06-26).

Casey: "we have comic bowling and rock bowling both at 6. they are the same
its cosmic bowling."

Two representations of the SAME Havasu Lanes glow-bowling night collide:

  * ``Family Cosmic Bowling`` (Fri 6-9pm) + ``Cosmic Bowling`` (Sat 9pm) — from
    the curated ``app/contrib/lhc_funzone.py`` loader. It uses a 7-DAY rolling
    window and is NOT on any cron, so it only ever covers the *current* week
    (right now: 2026-06-26 Fri + 2026-06-27 Sat). The descriptions are generic.
  * ``Rock & Bowl - Family Glow Bowling`` — 17 dated rows, Fri AND Sat 6-11pm,
    running through 2026-08-07, with the richer real description (pricing,
    shoes, bumper bowling). Titles are clean (a real em-dash, not mojibake).
    Loaded once by the youth-calendar commit; also not regenerated by a cron.

Because the funzone set has no future coverage, we KEEP the Rock & Bowl series
(it carries every future date) but RENAME it to the canonical name Casey gave,
"Cosmic Bowling", and DELETE the two funzone rows that collide this week. The
result is a single clean "Cosmic Bowling" series, Fri+Sat 6-11pm, through Aug 7.

Neither set is cron-regenerated, so the change sticks.

Read-only by default. Pass --apply to perform the rename + delete.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy import func  # noqa: E402

from app.db.database import SessionLocal  # noqa: E402
from app.db.models import Event  # noqa: E402

# The Rock & Bowl occurrences all carry this slug in their source_url
# (e.g. https://www.havasulanesaz.com/specials?occ=rock-and-bowl-2026-06-12).
ROCK_AND_BOWL_URL_NEEDLE = "rock-and-bowl"
NEW_TITLE = "Cosmic Bowling"

# The two funzone rows to retire (selected by their synthetic source_anchor
# marker so we never touch anything else): "...|family cosmic bowling|..." and
# "...|cosmic bowling|...".
FUNZONE_URL_NEEDLE = "#funspecial"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--apply", action="store_true", help="Perform the writes (default: dry run).")
    args = ap.parse_args()

    db = SessionLocal()
    try:
        rename = (
            db.query(Event)
            .filter(func.lower(Event.source_url).like(f"%{ROCK_AND_BOWL_URL_NEEDLE}%"))
            .order_by(Event.date)
            .all()
        )
        delete = (
            db.query(Event)
            .filter(func.lower(Event.source_url).like(f"%{FUNZONE_URL_NEEDLE}%"))
            .filter(func.lower(Event.title).like("%cosmic bowling%"))
            .order_by(Event.date)
            .all()
        )

        print(f"RENAME -> {NEW_TITLE!r} ({len(rename)} Rock & Bowl rows):")
        for r in rename:
            print(f"  id={r.id[:8]} date={r.date} {r.start_time}-{r.end_time} {r.title!r}")

        print(f"\nDELETE (funzone collide rows, {len(delete)}):")
        for r in delete:
            print(f"  id={r.id[:8]} date={r.date} {r.start_time}-{r.end_time} {r.title!r} url={r.source_url!r}")

        # Safety rails: refuse if the selection looks wrong.
        bad_rename = [r for r in rename if "bowl" not in (r.title or "").lower()]
        bad_delete = [r for r in delete if "cosmic bowling" not in (r.title or "").lower()]
        if bad_rename or bad_delete:
            print(f"\nABORT: unexpected selection (rename={len(bad_rename)} delete={len(bad_delete)}).")
            return 2
        if not rename:
            print("\nABORT: no Rock & Bowl rows found to rename — refusing to only delete.")
            return 2

        if not args.apply:
            print(f"\nDRY RUN - would rename {len(rename)} and delete {len(delete)} rows. "
                  f"Re-run with --apply.")
            return 0

        for r in rename:
            r.title = NEW_TITLE
            r.normalized_title = NEW_TITLE.lower().strip()
        for r in delete:
            db.delete(r)
        db.commit()
        print(f"\nAPPLIED - renamed {len(rename)} rows to {NEW_TITLE!r}, deleted {len(delete)} funzone rows.")
        return 0
    finally:
        db.close()


if __name__ == "__main__":
    raise SystemExit(main())
